server:
  port: 8882
  servlet:
    context-path: /recordservice
logging:
  config: classpath:log4j2.xml
  level:
    com.dyz.filxeservice.client.LogicFileClient: DEBUG
spring:
  application:
    name: recordservice
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
eureka:
  instance:
    # 使用服务的IP而不是服务器名称，确保在容器环境下正常
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/