server:
  port: 8882
  servlet:
    context-path: /
logging:
  file: /Volumes/DYZ-document/Program/X-CodeRunSpace/log/recordservice/record-service.log
  level:
    com.dyz.filxeservice.client.LogicFileClient: DEBUG
    com.dyz.commentservice.client.CommentClient: DEBUG
spring:
  application:
    name: recordservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DMS_DB_HOST:127.0.0.1}:3306/recorddb?charset=utf8mb4&useSSL=false
    username: ${DMS_DB_USERNAME:root}
    password: ${DMS_DB_PASSWORD:658080}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
eureka:
  instance:
    # 使用服务的IP而不是服务器名称，确保在容器环境下正常
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DMS_DISCOVER_HOST:127.0.0.1}:8761/eureka/