filxeservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    ConnectTimeout: 500 #请求连接超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
commentservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    ConnectTimeout: 500 #请求连接超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数


#com.netflix.loadbalancer.RandomRule # 随机选择服务实例
#com.netflix.loadbalancer.RoundRobinRule # 轮询模式，按顺序选择服务实例
#com.netflix.loadbalancer.RetryRule # 重试
#com.netflix.loadbalancer.WeightedResponseTimeRule # 首先采用轮询方式，然后采集响应时间，按照响应时间权重选择服务
#com.netflix.loadbalancer.BestAvailableRule # 最空闲连接策略